name: README Update

on:
  push:      # run @ every push
  schedule:
    - cron: '0 1,12,18 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute render.py script 
        env: 
          openweather_api_key: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python render.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update README"
          # git push origin main
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main 
